# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-26 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('rut', models.CharField(max_length=20, verbose_name='Rut')),
                ('digito_verificador', models.CharField(max_length=1, verbose_name='D\xedgito verificador')),
                ('telefono', models.CharField(max_length=100, verbose_name='T\xe9lefono')),
                ('direccion', models.CharField(max_length=300, verbose_name='Direcci\xf3n')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripci\xf3n')),
            ],
        ),
    ]
