# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-14 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('direccion', models.CharField(max_length=300, verbose_name='Direcci\xf3n')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('pais', models.CharField(max_length=100, verbose_name='Pa\xeds')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
                ('telefono', models.CharField(max_length=100, verbose_name='T\xe9lefono')),
                ('rut', models.CharField(max_length=1, verbose_name='Rut')),
                ('digito_verificador', models.CharField(max_length=1, verbose_name='D\xedgito verificador')),
            ],
        ),
    ]
