# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-16 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20180115_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(max_length=8, verbose_name='Rut'),
        ),
    ]
