# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-25 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_cliente_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(max_length=20, verbose_name='Rut'),
        ),
    ]
