# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-28 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_auto_20180125_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='PotencialCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=300, verbose_name='Nombre Completo')),
                ('email', models.CharField(max_length=100, null=True, verbose_name='E-mail')),
                ('telefono', models.CharField(max_length=100, null=True, verbose_name='Tel\xe9fono')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripci\xf3n')),
            ],
        ),
    ]
