# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-01 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_potencialcliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='potencialcliente',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='potencialcliente',
            name='nacionalidad',
            field=models.CharField(default='', max_length=100, verbose_name='Nacionalidad'),
            preserve_default=False,
        ),
    ]
