# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-03 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_auto_20180201_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potencialcliente',
            name='descripcion',
            field=models.CharField(max_length=500, null=True, verbose_name='Descripci\xf3n'),
        ),
    ]
