# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-26 11:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cliente', '0010_auto_20180221_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('modelo', models.CharField(choices=[('cl', 'Cliente'), ('pcl', 'PotencialCliente'), ('emp', 'Empresa')], max_length=4)),
                ('modelo_id', models.PositiveIntegerField()),
                ('_info', models.TextField(default='{}')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='log',
            name='user',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
    ]
