# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-21 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alojamiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocupacionalojamiento',
            name='cautiva',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ocupacionalojamiento',
            name='reservaalojamiento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='alojamiento.ReservaAlojamiento'),
            preserve_default=False,
        ),
    ]
