# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-26 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
        ('alojamiento', '0002_auto_20180221_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservaalojamiento',
            name='cliente_secundario',
        ),
        migrations.AddField(
            model_name='reservaalojamiento',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='empresa.Empresa'),
        ),
        migrations.AlterField(
            model_name='reservaalojamiento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cliente.Cliente'),
        ),
    ]
