# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-06 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamiento', '0006_alojamiento_habilitado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocupacionalojamiento',
            name='_info',
        ),
        migrations.RemoveField(
            model_name='reservaalojamiento',
            name='canalventa',
        ),
        migrations.AddField(
            model_name='ocupacionalojamiento',
            name='cantidad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservaalojamiento',
            name='estado',
            field=models.CharField(choices=[('confirmando_pago', 'Confirmando pago'), ('pagada', 'Pagada'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], max_length=30),
        ),
    ]
