# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-08 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamiento', '0008_auto_20180307_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='reservaalojamiento',
            name='_comentario',
            field=models.TextField(default='{}'),
        ),
    ]
